# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 697)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.param_tau = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_tau.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.param_tau.setDecimals(3)
        self.param_tau.setMinimum(-99.99)
        self.param_tau.setProperty("value", 1.0)
        self.param_tau.setObjectName("param_tau")
        self.gridLayout.addWidget(self.param_tau, 1, 1, 1, 1)
        self.param_r0_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_r0_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.param_r0_3.setDecimals(3)
        self.param_r0_3.setMinimum(-99.99)
        self.param_r0_3.setObjectName("param_r0_3")
        self.gridLayout.addWidget(self.param_r0_3, 4, 1, 1, 1)
        self.param_r0_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_r0_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.param_r0_2.setDecimals(3)
        self.param_r0_2.setMinimum(-99.99)
        self.param_r0_2.setObjectName("param_r0_2")
        self.gridLayout.addWidget(self.param_r0_2, 3, 1, 1, 1)
        self.param_r0_1 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_r0_1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.param_r0_1.setDecimals(3)
        self.param_r0_1.setMinimum(-99.99)
        self.param_r0_1.setObjectName("param_r0_1")
        self.gridLayout.addWidget(self.param_r0_1, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.param_total_time = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.param_total_time.setMaximum(1000)
        self.param_total_time.setProperty("value", 10)
        self.param_total_time.setObjectName("param_total_time")
        self.gridLayout.addWidget(self.param_total_time, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.radioButton_linear = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_linear.setChecked(True)
        self.radioButton_linear.setObjectName("radioButton_linear")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_linear)
        self.verticalLayout.addWidget(self.radioButton_linear)
        self.radioButton_nonlinear = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_nonlinear.setObjectName("radioButton_nonlinear")
        self.buttonGroup.addButton(self.radioButton_nonlinear)
        self.verticalLayout.addWidget(self.radioButton_nonlinear)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.param_max_rate = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.param_max_rate.setMinimum(-1000)
        self.param_max_rate.setMaximum(1000)
        self.param_max_rate.setProperty("value", 100)
        self.param_max_rate.setObjectName("param_max_rate")
        self.gridLayout_3.addWidget(self.param_max_rate, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.param_sigma = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.param_sigma.setMinimum(-1000)
        self.param_sigma.setMaximum(1000)
        self.param_sigma.setProperty("value", 40)
        self.param_sigma.setObjectName("param_sigma")
        self.gridLayout_3.addWidget(self.param_sigma, 1, 2, 1, 1)
        self.param_steepness = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.param_steepness.setMinimum(-1000)
        self.param_steepness.setMaximum(1000)
        self.param_steepness.setProperty("value", 2)
        self.param_steepness.setObjectName("param_steepness")
        self.gridLayout_3.addWidget(self.param_steepness, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.checkBox_adaptation = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_adaptation.setObjectName("checkBox_adaptation")
        self.gridLayout_3.addWidget(self.checkBox_adaptation, 3, 1, 1, 1)
        self.param_adaptation_strength = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_adaptation_strength.setProperty("value", 1.0)
        self.param_adaptation_strength.setObjectName("param_adaptation_strength")
        self.gridLayout_3.addWidget(self.param_adaptation_strength, 5, 2, 1, 1)
        self.param_adaptation_tau = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.param_adaptation_tau.setDecimals(3)
        self.param_adaptation_tau.setMaximum(999.99)
        self.param_adaptation_tau.setProperty("value", 100.0)
        self.param_adaptation_tau.setObjectName("param_adaptation_tau")
        self.gridLayout_3.addWidget(self.param_adaptation_tau, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 630, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 10, 389, 571))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kalman_noise_proc = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.kalman_noise_proc.setProperty("value", 1.0)
        self.kalman_noise_proc.setObjectName("kalman_noise_proc")
        self.gridLayout_2.addWidget(self.kalman_noise_proc, 10, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 0, 1, 1)
        self.checkBox_kalman = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_kalman.setObjectName("checkBox_kalman")
        self.gridLayout_2.addWidget(self.checkBox_kalman, 8, 0, 1, 1)
        self.kalman_noise_meas = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.kalman_noise_meas.setProperty("value", 1.0)
        self.kalman_noise_meas.setObjectName("kalman_noise_meas")
        self.gridLayout_2.addWidget(self.kalman_noise_meas, 9, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 11, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 0, 1, 1)
        self.param_noise_mean = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.param_noise_mean.setFont(font)
        self.param_noise_mean.setMinimum(-99.0)
        self.param_noise_mean.setObjectName("param_noise_mean")
        self.gridLayout_2.addWidget(self.param_noise_mean, 6, 1, 1, 1)
        self.param_noise_stddev = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.param_noise_stddev.setProperty("value", 1.0)
        self.param_noise_stddev.setObjectName("param_noise_stddev")
        self.gridLayout_2.addWidget(self.param_noise_stddev, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 7, 0, 1, 1)
        self.stimulus_off_val = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.stimulus_off_val.setMinimum(-99.0)
        self.stimulus_off_val.setObjectName("stimulus_off_val")
        self.gridLayout_2.addWidget(self.stimulus_off_val, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.stimulus_frequency = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.stimulus_frequency.setObjectName("stimulus_frequency")
        self.gridLayout_2.addWidget(self.stimulus_frequency, 1, 1, 1, 1)
        self.checkBox_noise = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_noise.setObjectName("checkBox_noise")
        self.gridLayout_2.addWidget(self.checkBox_noise, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.stimulus_on_val = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.stimulus_on_val.setMinimum(-99.0)
        self.stimulus_on_val.setProperty("value", 0.0)
        self.stimulus_on_val.setObjectName("stimulus_on_val")
        self.gridLayout_2.addWidget(self.stimulus_on_val, 3, 1, 1, 1)
        self.stimulus_duty = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.stimulus_duty.setMaximum(1.0)
        self.stimulus_duty.setProperty("value", 0.5)
        self.stimulus_duty.setObjectName("stimulus_duty")
        self.gridLayout_2.addWidget(self.stimulus_duty, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.kalman_init_p = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.kalman_init_p.setProperty("value", 1.0)
        self.kalman_init_p.setObjectName("kalman_init_p")
        self.gridLayout_2.addWidget(self.kalman_init_p, 11, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 12, 0, 1, 1)
        self.kalman_init_response = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.kalman_init_response.setMinimum(-99.0)
        self.kalman_init_response.setObjectName("kalman_init_response")
        self.gridLayout_2.addWidget(self.kalman_init_response, 12, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Timescale"))
        self.label_8.setText(_translate("Form", "Initial r2"))
        self.label_7.setText(_translate("Form", "Initial r1"))
        self.label_9.setText(_translate("Form", "Initial r3"))
        self.label_10.setText(_translate("Form", "Simulation Time"))
        self.label_5.setText(_translate("Form", "Model Linearity:"))
        self.radioButton_linear.setText(_translate("Form", "Linear"))
        self.radioButton_nonlinear.setText(_translate("Form", "Non-Linear (Naka-Rushton)\n"
"With the parameters below:"))
        self.label_2.setText(_translate("Form", "Maximum Firing Rate"))
        self.label_3.setText(_translate("Form", "Sigma (spread)"))
        self.label_4.setText(_translate("Form", "Steepness"))
        self.checkBox_adaptation.setText(_translate("Form", "Use adaptation, with\n"
"these parameters:"))
        self.label_11.setText(_translate("Form", "Adaptation Timescale"))
        self.label_12.setText(_translate("Form", "Adaptation Strength"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label_19.setText(_translate("Form", "Measurement Noise\n"
"(Standard Deviation)"))
        self.checkBox_kalman.setText(_translate("Form", "Use a Kalman Filter\n"
"with these parameters:"))
        self.label_21.setText(_translate("Form", "Initial Uncertainty of Estimate\n"
"(Standard Deviation)"))
        self.label_20.setText(_translate("Form", "Estimate of Process Noise\n"
"(Standard Deviation)"))
        self.label.setText(_translate("Form", "Mean"))
        self.label_18.setText(_translate("Form", "Standard Deviation"))
        self.label_13.setText(_translate("Form", "Frequency (Hz)"))
        self.checkBox_noise.setText(_translate("Form", "Add Process Noise as\n"
"the following Gaussian:"))
        self.label_15.setText(_translate("Form", "ON Amplitude"))
        self.label_17.setText(_translate("Form", "Stimulus:"))
        self.label_14.setText(_translate("Form", "Duty Cycle"))
        self.label_16.setText(_translate("Form", "OFF Amplitude"))
        self.label_22.setText(_translate("Form", "Initial Response Estimate"))

