# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neuron_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 750))
        MainWindow.setMaximumSize(QtCore.QSize(650, 750))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("image: url(:/images/neurons.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.connection_2_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_2_1.setGeometry(QtCore.QRect(270, 260, 111, 41))
        self.connection_2_1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_2_1.setDecimals(3)
        self.connection_2_1.setMinimum(-99.99)
        self.connection_2_1.setObjectName("connection_2_1")
        self.connection_2_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_2_2.setGeometry(QtCore.QRect(440, 20, 111, 41))
        self.connection_2_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_2_2.setDecimals(3)
        self.connection_2_2.setMinimum(-99.99)
        self.connection_2_2.setObjectName("connection_2_2")
        self.connection_2_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_2_3.setGeometry(QtCore.QRect(330, 340, 111, 41))
        self.connection_2_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_2_3.setDecimals(3)
        self.connection_2_3.setMinimum(-99.99)
        self.connection_2_3.setObjectName("connection_2_3")
        self.connection_1_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_1_1.setGeometry(QtCore.QRect(100, 30, 111, 41))
        self.connection_1_1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_1_1.setDecimals(3)
        self.connection_1_1.setMinimum(-99.99)
        self.connection_1_1.setObjectName("connection_1_1")
        self.connection_1_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_1_2.setGeometry(QtCore.QRect(270, 90, 111, 41))
        self.connection_1_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_1_2.setDecimals(3)
        self.connection_1_2.setMinimum(-99.99)
        self.connection_1_2.setObjectName("connection_1_2")
        self.connection_1_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_1_3.setGeometry(QtCore.QRect(200, 340, 111, 41))
        self.connection_1_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_1_3.setDecimals(3)
        self.connection_1_3.setMinimum(-99.99)
        self.connection_1_3.setObjectName("connection_1_3")
        self.connection_3_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_3_1.setGeometry(QtCore.QRect(10, 400, 111, 41))
        self.connection_3_1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_3_1.setDecimals(3)
        self.connection_3_1.setMinimum(-99.99)
        self.connection_3_1.setObjectName("connection_3_1")
        self.connection_3_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_3_2.setGeometry(QtCore.QRect(530, 380, 111, 41))
        self.connection_3_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_3_2.setReadOnly(False)
        self.connection_3_2.setDecimals(3)
        self.connection_3_2.setMinimum(-99.99)
        self.connection_3_2.setObjectName("connection_3_2")
        self.connection_3_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.connection_3_3.setGeometry(QtCore.QRect(160, 630, 111, 41))
        self.connection_3_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connection_3_3.setDecimals(3)
        self.connection_3_3.setMinimum(-99.99)
        self.connection_3_3.setObjectName("connection_3_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 500, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(490, 570, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Calculate\n"
"Eigenvalues:"))

import qt_resources_rc
